# Generated by Django 2.2.6 on 2020-05-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_list_total_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='footer',
            field=models.CharField(default=222, max_length=1000),
            preserve_default=False,
        ),
    ]
