# Generated by Django 2.2.6 on 2020-05-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_list_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='total_words',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
